/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.App
import io.swagger.client.model.Error
import io.swagger.client.model.PageOfApp
import io.swagger.client.model.PageOfProduct
import io.swagger.client.model.PageOfUser
import io.swagger.client.model.Product
import io.swagger.client.model.RedirectAttributes
import io.swagger.client.model.User
import io.swagger.client.model.&#x60;Object&#x60;
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param id id
   */
  def auditUsingPOST(id: &#x60;Object&#x60;): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/app/audit/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : String (OK)
   * 
   * @param user user
   */
  def authorizeUsingPOST(user: User): ApiRequest[String] =
    ApiRequest[String](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/authorize", "*/*")
      .withBody(user)
      .withSuccessResponse[String](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param app app
   */
  def createUsingPOST(app: App): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/app/create", "*/*")
      .withBody(app)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param product product
   */
  def createUsingPOST1(product: Product): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/product/create", "*/*")
      .withBody(product)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param user user
   */
  def createUsingPOST3(user: User): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/user/create", "*/*")
      .withBody(user)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param id id
   */
  def deleteUsingDELETE(id: &#x60;Object&#x60;): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://auth.sinocloudlab.com", "/api/app/delete/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param id id
   */
  def deleteUsingDELETE1(id: &#x60;Object&#x60;): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://auth.sinocloudlab.com", "/api/product/delete/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param id id
   */
  def deleteUsingDELETE2(id: &#x60;Object&#x60;): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://auth.sinocloudlab.com", "/api/user/delete/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : App (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param appId appId
   */
  def detailUsingGET(appId: String): ApiRequest[App] =
    ApiRequest[App](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/app/query/{appId}", "*/*")
      .withPathParam("appId", appId)
      .withSuccessResponse[App](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : App (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param id id
   */
  def detailUsingGET1(id: &#x60;Object&#x60;): ApiRequest[App] =
    ApiRequest[App](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/app/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[App](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Product (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param id id
   */
  def detailUsingGET2(id: &#x60;Object&#x60;): ApiRequest[Product] =
    ApiRequest[Product](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/product/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[Product](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : User (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param id id
   */
  def detailUsingGET3(id: &#x60;Object&#x60;): ApiRequest[User] =
    ApiRequest[User](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/user/{id}", "*/*")
      .withPathParam("id", id)
      .withSuccessResponse[User](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Product (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param name name
   */
  def getByNameUsingGET(name: String): ApiRequest[Product] =
    ApiRequest[Product](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/product/getByName/{name}", "*/*")
      .withPathParam("name", name)
      .withSuccessResponse[Product](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Seq[Product] (OK)
   *   code 500 : Error (Internal Server Error)
   */
  def listAllUsingGET(): ApiRequest[Seq[Product]] =
    ApiRequest[Seq[Product]](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/product/listAll", "*/*")
      .withSuccessResponse[Seq[Product]](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : PageOfApp (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param user user
   * @param keyword keyword
   */
  def listUsingGET(user: String, keyword: String): ApiRequest[PageOfApp] =
    ApiRequest[PageOfApp](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/app/listUserApps", "*/*")
      .withQueryParam("user", user)
      .withQueryParam("keyword", keyword)
      .withSuccessResponse[PageOfApp](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : PageOfApp (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param keyword keyword
   */
  def listUsingGET1(keyword: String): ApiRequest[PageOfApp] =
    ApiRequest[PageOfApp](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/app/list", "*/*")
      .withQueryParam("keyword", keyword)
      .withSuccessResponse[PageOfApp](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : PageOfProduct (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param keyword keyword
   */
  def listUsingGET2(keyword: String): ApiRequest[PageOfProduct] =
    ApiRequest[PageOfProduct](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/product/list", "*/*")
      .withQueryParam("keyword", keyword)
      .withSuccessResponse[PageOfProduct](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : PageOfUser (OK)
   *   code 500 : Error (Internal Server Error)
   * 
   * @param keyword keyword
   */
  def listUsingGET3(keyword: String): ApiRequest[PageOfUser] =
    ApiRequest[PageOfUser](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/user/list", "*/*")
      .withQueryParam("keyword", keyword)
      .withSuccessResponse[PageOfUser](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : User (OK)
   * 
   * @param user user
   */
  def loginUsingPOST(user: User): ApiRequest[User] =
    ApiRequest[User](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/user/login", "*/*")
      .withBody(user)
      .withSuccessResponse[User](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   *   code 500 : Error (Internal Server Error)
   */
  def logoutUsingGET(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://auth.sinocloudlab.com", "/api/user/logout", "*/*")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Error](500)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : String (OK)
   * 
   * @param id id
   * @param newPassword newPassword
   * @param redirectAttributes redirectAttributes
   */
  def modifyPasswordUsingPOST(id: &#x60;Object&#x60;, newPassword: Option[String] = None, redirectAttributes: Option[RedirectAttributes] = None): ApiRequest[String] =
    ApiRequest[String](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/user/modifyPassword/{id}", "*/*")
      .withBody(redirectAttributes)
      .withPathParam("id", id)
      .withSuccessResponse[String](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param app app
   */
  def updateUsingPOST(app: App): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/app/update", "*/*")
      .withBody(app)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param product product
   */
  def updateUsingPOST1(product: Product): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/product/update", "*/*")
      .withBody(product)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param user user
   */
  def updateUsingPOST2(user: User): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://auth.sinocloudlab.com", "/api/user/update", "*/*")
      .withBody(user)
      .withSuccessResponse[Unit](200)
      

}

