/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class App (
  accessToken: Option[String],
  appId: Option[String],
  appName: Option[String],
  appSecret: Option[String],
  bindProduct: Option[String],
  create: Option[String],
  expired: Option[Long],
  id: Option[ObjectId],
  modify: Option[String],
  refreshToken: Option[String],
  scopes: Option[Seq[String]],
  state: Option[AppEnums.State],
  user: Option[String],
  version: Option[Int]
) extends ApiModel

object AppEnums {

  type State = State.Value
  object State extends Enumeration {
    val Initial = Value("initial")
    val Auditing = Value("auditing")
    val Audited = Value("audited")
  }

}

