/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class User (
  accountNonExpired: Option[Boolean],
  accountNonLocked: Option[Boolean],
  authorities: Option[CollectionOfGrantedAuthority],
  credentialsNonExpired: Option[Boolean],
  email: Option[String],
  enabled: Option[Boolean],
  id: Option[ObjectId],
  lastLogin: Option[String],
  modify: Option[String],
  password: Option[String],
  register: Option[String],
  roles: Option[UserEnums.Seq[Roles]],
  username: Option[String],
  version: Option[Int]
) extends ApiModel

object UserEnums {

  type Seq[Roles] = Seq[Roles].Value
  object Seq[Roles] extends Enumeration {
  }

}

